[package]
name = "knifey-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.1"
fastrand = "1.7.0"
blake3 = "1.3.1"
quickcheck = { version = "1.0.3", default-features = false, features = [] }
rand = { version = "0.8.5", features = ["small_rng", "alloc"] }
