[package]
name = "knifey-service"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.7.0"
#serenity = "0.11.1"
serenity = { version = "0.11.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.18.0", features = ["full"] }
